runtime: php55
api_version: 1
service: fuentesexternasproveedores
threadsafe: true

handlers:

- url: /bootstrap-3.3.7-dist
  static_dir: bootstrap-3.3.7-dist

- url: /fonts
  static_dir: fonts

- url: /img
  static_dir: img
 
- url: /(.+\.(html|php))$
  script: \1

- url: /.*
  script: index.php

- url: /.*
  script: recuperar.php

- url: /.*
  script: herramientaAdmin.php
  
- url: /(.+)
  script: /
